SET IDENTITY_INSERT [dbo].[tbl_product] ON
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (7, N'AOne 1', N'This is the best feature phone available in the marker.', 10, N'Blue,Black,Red', 1, 1, 10, N'phone.jpg', 1, NULL)
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (8, N'AOne 2', N'This is the best feature phone available in the marker.', 10, N'Blue,Black,Red', 1, 1, 20, N'phone.jpg', 1, NULL)
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (9, N'AOne 3', N'This is the best feature phone available in the marker.', 10, N'Blue,Black,Red', 1, 1, 30, N'phone.jpg', 1, NULL)
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (10, N'AGrade 1', N'This is the best feature phone available in the marker.', 10, N'Blue,Black,Red', 1, 2, 40, N'phone.jpg', 2, NULL)
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (11, N'AGrade 2', N'This is the best feature phone available in the marker.', 10, N'Blue,Black,Red', 1, 2, 50, N'phone.jpg', 2, NULL)
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (12, N'AGrade 3', N'This is the best feature phone available in the marker.', 10, N'Blue,Black,Red', 1, 2, 60, N'phone.jpg', 2, NULL)
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (13, N'T Shirt', N'This is the best feature phone available in the marker.', 10, N'White,Black,Red', 2, 1, 100, N'shirt.jpg', 1, N'Small,Large,Medium')
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (14, N'Boxer', N'This is the best feature phone available in the marker.', 10, N'White,Black,Red', 2, 1, 200, N'shirt.jpg', 1, N'Small,Large,Medium')
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (15, N'Shirt', N'This is the best feature phone available in the marker.', 10, N'White,Black,Red', 2, 1, 300, N'shirt.jpg', 1, N'Small,Large,Medium')
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (16, N'Jeans', N'This is the best feature phone available in the marker.', 10, N'White,Black,Red', 2, 2, 400, N'shirt.jpg', 2, N'Small,Large,Medium')
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (17, N'Slim Jeans', N'This is the best feature phone available in the marker.', 10, N'White,Black,Red', 2, 2, 500, N'shirt.jpg', 2, N'Small,Large,Medium')
INSERT INTO [dbo].[tbl_product] ([Product_id], [Product_Name], [Product_Description], [Product_Available_Quantity], [Product_Available_Colors ], [Product_Category_Id], [Product_Company_Id], [Product_Price], [Url], [Product_Popularity], [Available_Size]) VALUES (18, N'Dry Fit T Shirt', N'This is the best feature phone available in the marker.', 10, N'White,Black,Red', 2, 2, 600, N'shirt.jpg', 2, N'Small,Large,Medium')
SET IDENTITY_INSERT [dbo].[tbl_product] OFF
