SET IDENTITY_INSERT [dbo].[tbl_menu] ON
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (1, N'Phones', N'Products', N'Phones', 0)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (2, N'Clothes', N'Products', N'Clothes', 0)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (3, N'Home Decor', N'Products', N'HomeDecor', 0)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (4, N'Grocery', N'Products', N'Phones', 0)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (5, N'Electronics', N'Products', N'Clothes', 0)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (6, N'Travel', N'Products', N'HomeDecor', 0)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (7, N'Samsung', N'Phones', N'Samsung', 1)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (8, N'Apple', N'Phones', N'Apple', 1)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (9, N'OnePlus', N'Phones', N'OnePlus', 1)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (10, N'Men', N'Clothes', N'Men', 2)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (11, N'Women', N'Clothes', N'Women', 2)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (12, N'Kids', N'Clothes', N'Kids', 2)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (13, N'Bedroom', N'HomeDecor', N'Bedroom', 3)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (14, N'Kitchen', N'HomeDecor', N'Kitchen', 3)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (15, N'Outdoor', N'HomeDecor', N'Outdoor', 3)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (16, N'Home', N'HomeDecor', N'Kitchen', 4)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (17, N'Office', N'HomeDecor', N'Outdoor', 4)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (18, N'Audio', N'HomeDecor', N'Kitchen', 5)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (19, N'Gaming', N'HomeDecor', N'Outdoor', 5)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (20, N'Flights', N'HomeDecor', N'Kitchen', 6)
INSERT INTO [dbo].[tbl_menu] ([Menu_id], [Menu_Name], [Controller], [Action], [Parent_menu_id]) VALUES (21, N'Trains', N'HomeDecor', N'Outdoor', 6)
SET IDENTITY_INSERT [dbo].[tbl_menu] OFF
